WORKSPACE
docs/stardoc_rule.md
stardoc/templates/markdown_tables/aspect.vm
stardoc/templates/markdown_tables/rule.vm
test/BUILD
test/testdata/android_basic_test/golden.txt
test/testdata/angle_bracket_test/golden.txt
test/testdata/apple_basic_test/golden.txt
test/testdata/aspect_test/golden.txt
test/testdata/attribute_defaults_test/golden.txt
test/testdata/attribute_defaults_test/input.bzl
test/testdata/attribute_types_test/golden.txt
test/testdata/cc_api_test/golden.txt
test/testdata/cpp_basic_test/golden.txt
test/testdata/filter_rules_test/golden.txt
test/testdata/function_basic_test/golden.txt
test/testdata/generated_bzl_test/golden.txt
test/testdata/java_basic_test/golden.txt
test/testdata/misc_apis_test/golden.txt
test/testdata/multiple_files_test/golden.txt
test/testdata/multiple_rules_test/golden.txt
test/testdata/proto_format_test/golden.raw
test/testdata/proto_format_test/golden.txt
test/testdata/providers_for_attributes_test/golden.txt
test/testdata/py_rule_test/golden.txt
test/testdata/repo_rules_test/golden.txt
test/testdata/same_level_file_test/golden.txt
test/testdata/simple_test/golden.txt
test/testdata/struct_default_value_test/golden.txt

This new cut includes:
Render defaults for non-mandatory rule and aspect attributes. (https://github.com/bazelbuild/bazel/commit/5eeccd8a647df10d154d3b86e9732e7f263c96db)

Update io_bazel dependency, jars, and tests

---

docs/stardoc_rule.md
stardoc/stardoc.bzl

So far as I can tell there is no skylark_library target, only a
bzl_library. Update the docs to reflect that.

Update docs to refer to bzl_library

---

stardoc/templates/html_tables/aspect.vm
stardoc/templates/html_tables/func.vm
stardoc/templates/html_tables/provider.vm
stardoc/templates/html_tables/rule.vm
test/testdata/html_tables_template_test/golden.md

GitHub flavored markdown permits markdown within HTML tags such as `<table>`, `<td>`, etc, as long as the HTML tags are 1) not indented more than 3 spaces and 2) are separated from the markdown by an empty line. (For the exact parsing rules see https://github.github.com/gfm/#html-blocks).

Modify HTML table templates to be GFM-friendly

---

WORKSPACE
test/testdata/attribute_types_test/golden.md
test/testdata/filter_rules_test/input.bzl
test/testdata/py_rule_test/golden.md
test/testdata/repo_rules_test/golden.md

Bazel 3.4 has a change in error prone that broke the compilation. This PR
updates the io_bazel dependency. I had to update a few other things to
get the tests passing.

Fix compilation of Stardoc, broken by Bazel 3.4

---

setup.bzl

The update includes a fix for the flag --incompatible_disable_depset_items.

Update Skylib dependency

---

WORKSPACE

This fixes Stardoc CI using a Bazel at HEAD.
Also ran buildifier on WORKSPACE, and updated shallow_since.

Update io_bazel dependency to reflect java_toolchain changes

---

WORKSPACE
test/testdata/local_repository_test/BUILD
test/testdata/local_repository_test/input.bzl

Documentation [here](https://github.com/bazelbuild/stardoc/blob/master/docs/getting_started_stardoc.md#setup) mentions this repo being loaded as `io_bazel_stardoc` whereas the real repo name is `io_bazel_skydoc`.

Update repository name to match documentation

---

stardoc/BUILD

Previously, there wasn't any `bzl_library` which included it. Which prevents further downstream `bzl_library`s from being defined with fully accurate deps.

Add bzl_library for html_tables_stardoc.bzl

---

CHANGELOG.md
version.bzl

We need a release containing the fix in https://github.com/bazelbuild/stardoc/pull/125

Prepare release 0.5.1 to fix missing zlib build failure

---

WORKSPACE
setup.bzl

For smaller download sizes and general user friendliness.
Note that we are for now using rules_java 4.0.0 instead of 5.0.0 due to https://github.com/bazelbuild/rules_java/issues/52

Use specific versioned tarballs of dependencies instead of git checkouts

---

stardoc/stardoc.bzl
test/testdata/misc_apis_test/input.bzl

See https://buildkite.com/bazel/stardoc/builds/454

Switch from cfg = "host" to cfg = "exec" to fix buildifier failures

---

WORKSPACE
docs/stardoc_rule.md
stardoc/proto/stardoc_output.proto
test/testdata/android_basic_test/golden.md
test/testdata/angle_bracket_test/golden.md
test/testdata/apple_basic_test/golden.md
test/testdata/aspect_test/golden.md
test/testdata/attribute_defaults_test/golden.md
test/testdata/attribute_types_test/golden.md
test/testdata/cc_api_test/golden.md
test/testdata/config_apis_test/golden.md
test/testdata/cpp_basic_test/golden.md
test/testdata/filter_rules_test/golden.md
test/testdata/generated_bzl_test/golden.md
test/testdata/html_tables_template_test/golden.md
test/testdata/input_template_test/golden.md
test/testdata/java_basic_test/golden.md
test/testdata/misc_apis_test/golden.md
test/testdata/multiple_files_test/golden.md
test/testdata/multiple_rules_test/golden.md
test/testdata/providers_for_attributes_test/golden.md
test/testdata/py_rule_test/golden.md
test/testdata/repo_rules_test/golden.md
test/testdata/same_level_file_test/golden.md
test/testdata/simple_test/golden.md

If you have a bzl file that contains
`@bazel_tools//tools/cpp/toolchain_utils.bzl`, after this commit
https://github.com/bazelbuild/bazel/commit/95f0135fbac934be696676f37e0285b2d311603a
stardoc stopped working because it didn't know about this API, leading
to this crash https://buildkite.com/bazel/rules-apple-darwin/builds/5829#0181f96c-ff6c-449e-936e-c32530bd3360
I assume this is because some of the stardoc internals pulls in the
older version of `ConfigStarlarkCommonApi.java`. This bumps the shas in
the first commit, and rebuilds them in the last commit. Feel free to
drop my rebuilds and do a more trusted rebuild.

Update bazel and rules_pkg

---

CHANGELOG.md
version.bzl

Prepare release 0.5.2 to fix crash on config_common.toolchain_type

---

docs/getting_started_stardoc.md

The doc in `docs/getting_started_stardoc.md` contained a link 'writing
extensions' that pointed to https://www.bazel.build/docs/skylark/concepts.html
This page returns a 404. I have updated the link to point to
https://bazel.build/extending/concepts , which seems to have the same contents
as the previous page as verified by a search on http://web.archive.org/

Fix 'extensions' link in getting_started_stardoc.md

---

stardoc/stardoc.bzl

There's currently a nuisance with the `stardoc()` rule that presents
itself in `rules_python`:
$ git clone https://github.com/bazelbuild/rules_python.git
$ cd rules_python
$ git checkout d314e96aaab18f60df50400d61214f7c1d71b8e6
$ bazel run //docs:update
cp: cannot stat 'bazel-bin/docs/packaging.md_': No such file or directory
cp: cannot stat 'bazel-bin/docs/pip.md_': No such file or directory
cp: cannot stat 'bazel-bin/docs/pip_repository.md_': No such file or directory
cp: cannot stat 'bazel-bin/docs/python.md_': No such file or directory
A sample of the targets involved look like so:
$ bazel cquery --output=build //docs:update + //docs:packaging-docs
INFO: Invocation ID: 5fd7a652-0b0d-4827-98f5-c345b38b2178
INFO: Analyzed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found …

Expose stardoc() output files as runfiles

---

WORKSPACE

Resolves config_setting visibility failures from https://github.com/bazelbuild/bazel/issues/12933:
ERROR: /var/lib/buildkite-agent/builds/bk-docker-zr2k/bazel-downstream-projects/stardoc/distro/BUILD:33:8: in
pkg_tar_impl rule //distro:distro_bins: target '@rules_pkg//pkg/private:private_stamp_detect' is not visible from
target '//distro:distro_bins'. Check the visibility declaration of the former target if you think the dependency is
legitimate
See https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1320#018435e1-7429-4329-808a-731599f24623.

Update rules_pkg to 0.8

---

WORKSPACE
bazel.patch

Fixes https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2824#0185bd7e-6fed-4c16-ad52-256b600d4ae3 for now. Updating bazel requires more work because of third party dependencies:
```
ERROR: /private/var/tmp/_bazel_ksmiley/430ca27aaa11819957cd32dd0f9637d8/external/io_bazel/third_party/BUILD:464:13: no such package '@maven//': The repository '@maven' could not be resolved: Repository '@maven' is not defined and referenced by '@io_bazel//third_party:guava'
```

Add bazel patch to work around underdefined dependency

---

BUILD
distro/BUILD
setup.bzl
stardoc/BUILD
stardoc/proto/BUILD
test/BUILD

Needed for bureaucratic compliance reasons.

Add license rules

---

test/bzlmod/def.bzl

Our internal system complains about the lack of license header in a .bzl file.

Add missing license blurb

---

CHANGELOG.md
MODULE.bazel
setup.bzl
version.bzl

Update rules_java dep to fix "No matching toolchains" errors with Bazel at HEAD, i.e. after https://github.com/bazelbuild/bazel/commit/975866a3e09212766bd353a90a8c42efe91d53ab
This error warrants an immediate release because it affects users of Stardoc releases, not just Stardoc itself.
See https://buildkite.com/bazel/bazel-skylib/builds/2692#0188728a-5bf4-4bb0-8d3a-6bc726a54f26 for an example failure.

Prepare release 0.5.5 with java toolchains breakage fix for Bazel at HEAD

---

CHANGELOG.md
MODULE.bazel
version.bzl

I forgot to bump the rules_java dep in MODULE.bazel.
We ought to have a consistency check for this...

Prepare release 0.5.6, now with java toolchains breakage fix with bzlmod too

---

.bazelci/presubmit.yml
CHANGELOG.md
MODULE.bazel
version.bzl

Needed for --incompatible_disable_starlark_host_transitions flag flip in Bazel 7
See #180

Prepare release 0.6.2

---

.bazelci/presubmit.yml

Use shared nodes for flags and task configs to avoid copy-pasting

Reorganize CI config to properly fix Windows workaround flags

---

docs/maintainers_guide.md
stardoc/BUILD
stardoc/stardoc.bzl
test/BUILD
test/bzlmod/def.bzl

* Add blurb about repository fetch errors
* Fix BCR text
* Recommend adding a commented MODULE.bazel setup block and uncommenting (easier than copy/pasting it later)
Fixes #186

Maintainer guide improvements

---

.bazelrc

This will help make sure [Bazel Downstream Pipeline](https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md) is green after enabling Bzlmod at Bazel@HEAD
See https://github.com/bazelbuild/bazel/issues/18958#issuecomment-1749058780
Related https://github.com/bazelbuild/stardoc/issues/189

Disable Bzlmod explicitly in .bazelrc

---

WORKSPACE
stardoc/proto/stardoc_output.proto
test/testdata/function_wrap_multiple_lines_test/legacy_golden.md

Required for the Stardoc's legacy doc extractor to behave consistently with Bazel 7 when stringifying @@-prefixed labels - see https://github.com/bazelbuild/bazel/issues/18543
Subsumes https://github.com/bazelbuild/stardoc/pull/193

Regenerate bundled legacy jar and proto for Bazel 7.0.1

---

test/testdata/providers_for_attributes_test/input.bzl
test/testdata/py_rule_test/input.bzl

We were explicitly testing it until now only because it was a builtin provider; we already have sufficient test coverage for Starlark providers.
Alternative to https://github.com/bazelbuild/stardoc/pull/194

Stop explicitly testing PyInfo - it's becoming an ordinary Starlark provider

---

test/testdata/stamping_test/golden.md
test/testdata/stamping_test/stamping_header.vm
update-stardoc-tests.sh

Internal linter complains about trailing spaces

Remove trailing space from stamping test, and filter it from update-stardoc-tests.sh script

---

src/main/java/com/google/devtools/build/skydoc/rendering/Stamping.java

... and we probably want buildKeepingLast to avoid unnecessary brittleness.
Fixes internal linter complaints.

ImmutableMap.Builder.build() is deprecated

---

BUILD

Required by internal license compliance checks.

Give LICENSE file export public visibility

---

src/main/java/com/google/devtools/build/skydoc/rendering/BUILD

Identified by internal linter.

trivial: Remove another unused visibility spec

---

test/bzlmod/BUILD
test/bzlmod/MODULE.bazel
test/bzlmod/def.bzl

Fixes the Stardoc part of https://github.com/bazelbuild/bazel/issues/21877.

Use new host platform constraints in test/bzlmod

---

BUILD
src/test/java/com/google/devtools/build/skydoc/rendering/BUILD

We already remove the integration tests from the distro tarball;
the rendering unit test is in there by mistake.

Remove rendering test from distro tarball

---

MODULE.bazel
src/main/java/com/google/devtools/build/skydoc/renderer/BUILD
src/main/java/com/google/devtools/build/skydoc/renderer/RendererMain.java

With `--incompatible_enable_proto_toolchain_resolution`, the root module is supposed to provide a `proto_lang_toolchain` for Java, which injects the runtime. Hardcoded dependencies on the `protobuf` module would negate the benefits of supplying a toolchain with precompiled `protoc` and runtime.
Since the only used symbol from the protobuf runtime was an exception class, it has been replaced with a check for its class name. If more protobuf runtime symbols should be needed in the future, they should be obtained from a `current_java_proto_runtime` target that first looks for a `proto_lang_toolchain` for Java and only then falls back to the hardcoded reference.
The WORKSPACE deps macro still brings in `com_google_protobuf` as this may be the only source of the repo for users.

Remove explicit dependency on protobuf

---

src/main/java/com/google/devtools/build/stardoc/renderer/RendererMain.java
src/main/java/com/google/devtools/build/stardoc/rendering/MarkdownRenderer.java
src/main/java/com/google/devtools/build/stardoc/rendering/MarkdownUtil.java
stardoc/templates/html_tables/provider.vm
stardoc/templates/markdown_tables/provider.vm
test/testdata/angle_bracket_test/golden.md
test/testdata/misc_apis_test/golden.md
test/testdata/provider_basic_test/golden.md
test/testdata/provider_basic_test/input.bzl
test/testdata/providers_for_attributes_test/golden.md
test/testdata/pure_markdown_template_test/golden.md
test/testdata/table_of_contents_test/golden.md

If a provider has a custom `init` callback, we want the summary blurb to show `init`'s parameters (since these are what the user will interact with); we have to render constructor paramaters and fields separately (and using separate html anchors) since there is not necessarily a 1-1 relationship between them, and since they may have different docs.
Fixes #182

Render documentation for provider `init` callbacks

---

.bazelci/presubmit.yml
test/BUILD
test/stardoc_test.bzl
update-stardoc-tests.sh

proto_format_test requires Bazel 7.1, and may break with other Bazel releases

---

.bazelci/presubmit.yml
docs/stardoc_rule.md
src/main/java/com/google/devtools/build/stardoc/rendering/MarkdownUtil.java
stardoc/proto/stardoc_output.proto
test/BUILD
test/testdata/macro_kwargs_test/golden.md
test/testdata/macro_kwargs_test/input.bzl
test/testdata/macro_kwargs_test/legacy_golden.md
update-stardoc-tests.sh

Fixes https://github.com/bazelbuild/stardoc/issues/225

Render *args / * / **kwargs properly in function summary line

---

.bazelci/presubmit.yml
test/BUILD
test/stardoc_test.bzl
update-stardoc-docs.sh
update-stardoc-tests.sh

Refactor stardoc_test() to create regenerator binaries for each golden test, and have update-stardoc-tests.sh query for those regenerator binaries and run them with the appropriate version of Bazel. As a side effect, this makes virtually all of Stardoc's tests auto-updateable, reducing maintenance burden.
Also take the opportunity to switch manual legacy tests from Bazel 7.1 to 7.2

Update test regeneration script to support multiple Bazel versions

---

.bazelci/presubmit.yml
.bazelrc
BUILD
distro/BUILD
stardoc/BUILD
test/bzlmod/.bazelrc

We always want to use some flags in development; e.g. an empty glob is a sign of a mistake, so we always want --incompatible_disallow_empty_glob
We will unconditionally set such flags in .bazelrc (not just in CI config).
For other incompatible flags (--incompatible_enable_proto_toolchain_resolution), we want to test builds both with and without them - and with bzlmod both enabled and disabled (see discussion in #236 for a case where this matters).
Such flags we will group under --config=incompatible, and test all 4 combinations (+- incompatible +- bzlmod) in CI.

Improve incompatible flag testing

---

.bazelci/presubmit.yml

Fixes #242 and https://github.com/bazelbuild/continuous-integration/issues/1999

Skip Bazel 7.2 tests in downstream pipeline

---

stardoc/stardoc.bzl

This pull request introduces changes to the `stardoc` macro to enhance its functionality by including user-defined tags in auxiliary targets. Previously, auxiliary targets only included default tags, and there was no way to specify additional tags.
1. **Tag Handling:**
- **Update:** Modified the `stardoc` macro to merge user-defined tags with default tags for auxiliary targets.
- **Default Behavior:** By default, auxiliary targets receive the `["manual"]` tag.
- **User-defined Tags:** If user-defined tags are provided, they are appended to the default tag list.
2. **Code Modifications:**
- **File Updated:** `stardoc/stardoc.bzl`
- **Details:** Added logic to handle the merging of tags in the `stardoc` macro. Ensured that user-defined tags are correctly 
combined with default tags before …

Merge user-defined tags with default tags in stardoc macro

---

.bazelci/presubmit.yml
test/BUILD

This means we need to enable workspace explicitly for legacy workspace tests - and mark local_repository_test as a legacy workspace test.
Fixes https://github.com/bazelbuild/stardoc/issues/250

Fix CI since --enable_workspace is now disabled by default in Bazel HEAD

---

test/testdata/apple_basic_test/input.bzl

Replace apple_common.AppleDynamicFramework in test/testdata/apple_basic_test with
apple_common.XcodeVersionConfig before apple_common.AppleDynamicFramework gets removed

Replace AppleDynamicFramework in test/testdata/apple_basic_test

---

.bazelci/presubmit.yml
.bazelrc
MODULE.bazel
WORKSPACE
deps.bzl
docs/maintainers_guide.md
setup.bzl
stardoc/proto/BUILD

The load for proto_library is missing, which breaks when used with Bazel 8.
Fixes https://github.com/bazelbuild/stardoc/issues/261

fix: add missing proto_library load to support Bazel 8

---

.bazelci/presubmit.yml
test/BUILD
test/testdata/angle_bracket_test/golden.md
test/testdata/aspect_test/golden.md
test/testdata/attribute_defaults_test/golden.md
test/testdata/html_tables_template_test/golden.md
test/testdata/input_template_test/golden.md
test/testdata/providers_for_attributes_test/input.bzl
test/testdata/pure_markdown_template_test/golden.md
test/testdata/table_of_contents_test/golden.md
update-stardoc-tests.sh

Remove unnecessary usage of ProtoInfo (which is no longer native and thus no longer needs special testing); enable tests requiring Bazel 8.0.0 by default; temporarily disable tests requiring Bazel 8.0.1 (more specifically - requiring starlark_doc_extract changes cherry-picked into 8.0.1 by https://github.com/bazelbuild/bazel/issues/24643) by default but test them using latest_green.

Fix CI failures

---

.bcr/config.yml
.bcr/metadata.template.json
.bcr/presubmit.yml
.bcr/source.template.json
.github/workflows/create_archive_and_notes.sh
.github/workflows/release.yml

This defines up a GitHub action to create a Github release and BCR configs for the Publish
To BCR app.
Creating a `X.Y.Z` tag will trigger the action.

chore: setup a github action to create releases
